// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user/v1/user_grpc.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_user_v1_user_grpc_proto protoreflect.FileDescriptor

const file_user_v1_user_grpc_proto_rawDesc = "" +
	"\n" +
	"\x17user/v1/user_grpc.proto\x12\vapi.user.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x12user/v1/user.proto2k\n" +
	"\vUserService\x12\\\n" +
	"\aGetUser\x12\x1b.api.user.v1.GetUserRequest\x1a\x1c.api.user.v1.GetUserResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/users/{id}B2Z0github.com/topcms/kratos-template/api/user/v1;v1b\x06proto3"

var file_user_v1_user_grpc_proto_goTypes = []any{
	(*GetUserRequest)(nil),  // 0: api.user.v1.GetUserRequest
	(*GetUserResponse)(nil), // 1: api.user.v1.GetUserResponse
}
var file_user_v1_user_grpc_proto_depIdxs = []int32{
	0, // 0: api.user.v1.UserService.GetUser:input_type -> api.user.v1.GetUserRequest
	1, // 1: api.user.v1.UserService.GetUser:output_type -> api.user.v1.GetUserResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_v1_user_grpc_proto_init() }
func file_user_v1_user_grpc_proto_init() {
	if File_user_v1_user_grpc_proto != nil {
		return
	}
	file_user_v1_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_user_grpc_proto_rawDesc), len(file_user_v1_user_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_user_grpc_proto_goTypes,
		DependencyIndexes: file_user_v1_user_grpc_proto_depIdxs,
	}.Build()
	File_user_v1_user_grpc_proto = out.File
	file_user_v1_user_grpc_proto_goTypes = nil
	file_user_v1_user_grpc_proto_depIdxs = nil
}
