// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user/v1/user.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserInfo 为用户信息实体。
type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserCode      string                 `protobuf:"bytes,2,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Gender        int32                  `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Introduction  string                 `protobuf:"bytes,6,opt,name=introduction,proto3" json:"introduction,omitempty"`
	RegType       int32                  `protobuf:"varint,7,opt,name=reg_type,json=regType,proto3" json:"reg_type,omitempty"`
	RegTime       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=reg_time,json=regTime,proto3" json:"reg_time,omitempty"`
	RegIp         int32                  `protobuf:"varint,9,opt,name=reg_ip,json=regIp,proto3" json:"reg_ip,omitempty"`
	Country       string                 `protobuf:"bytes,10,opt,name=country,proto3" json:"country,omitempty"`
	Province      string                 `protobuf:"bytes,11,opt,name=province,proto3" json:"province,omitempty"`
	City          string                 `protobuf:"bytes,12,opt,name=city,proto3" json:"city,omitempty"`
	Lang          string                 `protobuf:"bytes,13,opt,name=lang,proto3" json:"lang,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsDel         int32                  `protobuf:"varint,16,opt,name=is_del,json=isDel,proto3" json:"is_del,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserInfo) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

func (x *UserInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfo) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserInfo) GetIntroduction() string {
	if x != nil {
		return x.Introduction
	}
	return ""
}

func (x *UserInfo) GetRegType() int32 {
	if x != nil {
		return x.RegType
	}
	return 0
}

func (x *UserInfo) GetRegTime() *timestamppb.Timestamp {
	if x != nil {
		return x.RegTime
	}
	return nil
}

func (x *UserInfo) GetRegIp() int32 {
	if x != nil {
		return x.RegIp
	}
	return 0
}

func (x *UserInfo) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *UserInfo) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *UserInfo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UserInfo) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *UserInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UserInfo) GetIsDel() int32 {
	if x != nil {
		return x.IsDel
	}
	return 0
}

// UserList 为用户列表数据结构。
type UserList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*UserInfo            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserList) Reset() {
	*x = UserList{}
	mi := &file_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserList) ProtoMessage() {}

func (x *UserList) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserList.ProtoReflect.Descriptor instead.
func (*UserList) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserList) GetList() []*UserInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *UserList) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// ReqUserDetail 单个用户查询请求。
type ReqUserDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqUserDetail) Reset() {
	*x = ReqUserDetail{}
	mi := &file_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqUserDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUserDetail) ProtoMessage() {}

func (x *ReqUserDetail) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUserDetail.ProtoReflect.Descriptor instead.
func (*ReqUserDetail) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *ReqUserDetail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// RspUserDetail 单个用户查询响应。
type RspUserDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspUserDetail) Reset() {
	*x = RspUserDetail{}
	mi := &file_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspUserDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspUserDetail) ProtoMessage() {}

func (x *RspUserDetail) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspUserDetail.ProtoReflect.Descriptor instead.
func (*RspUserDetail) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *RspUserDetail) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

// ReqUserCreate 用户新增请求。
type ReqUserCreate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqUserCreate) Reset() {
	*x = ReqUserCreate{}
	mi := &file_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqUserCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUserCreate) ProtoMessage() {}

func (x *ReqUserCreate) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUserCreate.ProtoReflect.Descriptor instead.
func (*ReqUserCreate) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *ReqUserCreate) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

// RspUserCreate 用户新增响应。
type RspUserCreate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspUserCreate) Reset() {
	*x = RspUserCreate{}
	mi := &file_user_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspUserCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspUserCreate) ProtoMessage() {}

func (x *RspUserCreate) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspUserCreate.ProtoReflect.Descriptor instead.
func (*RspUserCreate) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *RspUserCreate) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

// ReqUserUpdate 用户更新请求。
type ReqUserUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserCode      *string                `protobuf:"bytes,2,opt,name=user_code,json=userCode,proto3,oneof" json:"user_code,omitempty"`
	UserName      *string                `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3,oneof" json:"user_name,omitempty"`
	Avatar        *string                `protobuf:"bytes,4,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	Gender        *int32                 `protobuf:"varint,5,opt,name=gender,proto3,oneof" json:"gender,omitempty"`
	Introduction  *string                `protobuf:"bytes,6,opt,name=introduction,proto3,oneof" json:"introduction,omitempty"`
	RegType       *int32                 `protobuf:"varint,7,opt,name=reg_type,json=regType,proto3,oneof" json:"reg_type,omitempty"`
	RegTime       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=reg_time,json=regTime,proto3" json:"reg_time,omitempty"`
	RegIp         *int32                 `protobuf:"varint,9,opt,name=reg_ip,json=regIp,proto3,oneof" json:"reg_ip,omitempty"`
	Country       *string                `protobuf:"bytes,10,opt,name=country,proto3,oneof" json:"country,omitempty"`
	Province      *string                `protobuf:"bytes,11,opt,name=province,proto3,oneof" json:"province,omitempty"`
	City          *string                `protobuf:"bytes,12,opt,name=city,proto3,oneof" json:"city,omitempty"`
	Lang          *string                `protobuf:"bytes,13,opt,name=lang,proto3,oneof" json:"lang,omitempty"`
	IsDel         *int32                 `protobuf:"varint,14,opt,name=is_del,json=isDel,proto3,oneof" json:"is_del,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqUserUpdate) Reset() {
	*x = ReqUserUpdate{}
	mi := &file_user_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqUserUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUserUpdate) ProtoMessage() {}

func (x *ReqUserUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUserUpdate.ProtoReflect.Descriptor instead.
func (*ReqUserUpdate) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *ReqUserUpdate) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReqUserUpdate) GetUserCode() string {
	if x != nil && x.UserCode != nil {
		return *x.UserCode
	}
	return ""
}

func (x *ReqUserUpdate) GetUserName() string {
	if x != nil && x.UserName != nil {
		return *x.UserName
	}
	return ""
}

func (x *ReqUserUpdate) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

func (x *ReqUserUpdate) GetGender() int32 {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return 0
}

func (x *ReqUserUpdate) GetIntroduction() string {
	if x != nil && x.Introduction != nil {
		return *x.Introduction
	}
	return ""
}

func (x *ReqUserUpdate) GetRegType() int32 {
	if x != nil && x.RegType != nil {
		return *x.RegType
	}
	return 0
}

func (x *ReqUserUpdate) GetRegTime() *timestamppb.Timestamp {
	if x != nil {
		return x.RegTime
	}
	return nil
}

func (x *ReqUserUpdate) GetRegIp() int32 {
	if x != nil && x.RegIp != nil {
		return *x.RegIp
	}
	return 0
}

func (x *ReqUserUpdate) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *ReqUserUpdate) GetProvince() string {
	if x != nil && x.Province != nil {
		return *x.Province
	}
	return ""
}

func (x *ReqUserUpdate) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *ReqUserUpdate) GetLang() string {
	if x != nil && x.Lang != nil {
		return *x.Lang
	}
	return ""
}

func (x *ReqUserUpdate) GetIsDel() int32 {
	if x != nil && x.IsDel != nil {
		return *x.IsDel
	}
	return 0
}

// RspUserUpdate 用户更新响应。
type RspUserUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspUserUpdate) Reset() {
	*x = RspUserUpdate{}
	mi := &file_user_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspUserUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspUserUpdate) ProtoMessage() {}

func (x *RspUserUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspUserUpdate.ProtoReflect.Descriptor instead.
func (*RspUserUpdate) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *RspUserUpdate) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

// ReqUserList 用户列表查询请求。
type ReqUserList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqUserList) Reset() {
	*x = ReqUserList{}
	mi := &file_user_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqUserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUserList) ProtoMessage() {}

func (x *ReqUserList) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUserList.ProtoReflect.Descriptor instead.
func (*ReqUserList) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *ReqUserList) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ReqUserList) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// RspUserList 用户列表查询响应。
type RspUserList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*UserInfo            `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspUserList) Reset() {
	*x = RspUserList{}
	mi := &file_user_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspUserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspUserList) ProtoMessage() {}

func (x *RspUserList) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspUserList.ProtoReflect.Descriptor instead.
func (*RspUserList) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *RspUserList) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *RspUserList) GetList() []*UserInfo {
	if x != nil {
		return x.List
	}
	return nil
}

var File_user_v1_user_proto protoreflect.FileDescriptor

const file_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x12user/v1/user.proto\x12\vapi.user.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x04\n" +
	"\bUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tuser_code\x18\x02 \x01(\tR\buserCode\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\x05R\x06gender\x12\"\n" +
	"\fintroduction\x18\x06 \x01(\tR\fintroduction\x12\x19\n" +
	"\breg_type\x18\a \x01(\x05R\aregType\x125\n" +
	"\breg_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\aregTime\x12\x15\n" +
	"\x06reg_ip\x18\t \x01(\x05R\x05regIp\x12\x18\n" +
	"\acountry\x18\n" +
	" \x01(\tR\acountry\x12\x1a\n" +
	"\bprovince\x18\v \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\f \x01(\tR\x04city\x12\x12\n" +
	"\x04lang\x18\r \x01(\tR\x04lang\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x15\n" +
	"\x06is_del\x18\x10 \x01(\x05R\x05isDel\"K\n" +
	"\bUserList\x12)\n" +
	"\x04list\x18\x01 \x03(\v2\x15.api.user.v1.UserInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x1f\n" +
	"\rReqUserDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\":\n" +
	"\rRspUserDetail\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.api.user.v1.UserInfoR\x04user\":\n" +
	"\rReqUserCreate\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.api.user.v1.UserInfoR\x04user\":\n" +
	"\rRspUserCreate\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.api.user.v1.UserInfoR\x04user\"\xe1\x04\n" +
	"\rReqUserUpdate\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12 \n" +
	"\tuser_code\x18\x02 \x01(\tH\x00R\buserCode\x88\x01\x01\x12 \n" +
	"\tuser_name\x18\x03 \x01(\tH\x01R\buserName\x88\x01\x01\x12\x1b\n" +
	"\x06avatar\x18\x04 \x01(\tH\x02R\x06avatar\x88\x01\x01\x12\x1b\n" +
	"\x06gender\x18\x05 \x01(\x05H\x03R\x06gender\x88\x01\x01\x12'\n" +
	"\fintroduction\x18\x06 \x01(\tH\x04R\fintroduction\x88\x01\x01\x12\x1e\n" +
	"\breg_type\x18\a \x01(\x05H\x05R\aregType\x88\x01\x01\x125\n" +
	"\breg_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\aregTime\x12\x1a\n" +
	"\x06reg_ip\x18\t \x01(\x05H\x06R\x05regIp\x88\x01\x01\x12\x1d\n" +
	"\acountry\x18\n" +
	" \x01(\tH\aR\acountry\x88\x01\x01\x12\x1f\n" +
	"\bprovince\x18\v \x01(\tH\bR\bprovince\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\f \x01(\tH\tR\x04city\x88\x01\x01\x12\x17\n" +
	"\x04lang\x18\r \x01(\tH\n" +
	"R\x04lang\x88\x01\x01\x12\x1a\n" +
	"\x06is_del\x18\x0e \x01(\x05H\vR\x05isDel\x88\x01\x01B\f\n" +
	"\n" +
	"_user_codeB\f\n" +
	"\n" +
	"_user_nameB\t\n" +
	"\a_avatarB\t\n" +
	"\a_genderB\x0f\n" +
	"\r_introductionB\v\n" +
	"\t_reg_typeB\t\n" +
	"\a_reg_ipB\n" +
	"\n" +
	"\b_countryB\v\n" +
	"\t_provinceB\a\n" +
	"\x05_cityB\a\n" +
	"\x05_langB\t\n" +
	"\a_is_del\":\n" +
	"\rRspUserUpdate\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.api.user.v1.UserInfoR\x04user\"5\n" +
	"\vReqUserList\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"N\n" +
	"\vRspUserList\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12)\n" +
	"\x04list\x18\x02 \x03(\v2\x15.api.user.v1.UserInfoR\x04listB2Z0github.com/topcms/kratos-template/api/user/v1;v1b\x06proto3"

var (
	file_user_v1_user_proto_rawDescOnce sync.Once
	file_user_v1_user_proto_rawDescData []byte
)

func file_user_v1_user_proto_rawDescGZIP() []byte {
	file_user_v1_user_proto_rawDescOnce.Do(func() {
		file_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)))
	})
	return file_user_v1_user_proto_rawDescData
}

var file_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_user_v1_user_proto_goTypes = []any{
	(*UserInfo)(nil),              // 0: api.user.v1.UserInfo
	(*UserList)(nil),              // 1: api.user.v1.UserList
	(*ReqUserDetail)(nil),         // 2: api.user.v1.ReqUserDetail
	(*RspUserDetail)(nil),         // 3: api.user.v1.RspUserDetail
	(*ReqUserCreate)(nil),         // 4: api.user.v1.ReqUserCreate
	(*RspUserCreate)(nil),         // 5: api.user.v1.RspUserCreate
	(*ReqUserUpdate)(nil),         // 6: api.user.v1.ReqUserUpdate
	(*RspUserUpdate)(nil),         // 7: api.user.v1.RspUserUpdate
	(*ReqUserList)(nil),           // 8: api.user.v1.ReqUserList
	(*RspUserList)(nil),           // 9: api.user.v1.RspUserList
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_user_v1_user_proto_depIdxs = []int32{
	10, // 0: api.user.v1.UserInfo.reg_time:type_name -> google.protobuf.Timestamp
	10, // 1: api.user.v1.UserInfo.created_at:type_name -> google.protobuf.Timestamp
	10, // 2: api.user.v1.UserInfo.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: api.user.v1.UserList.list:type_name -> api.user.v1.UserInfo
	0,  // 4: api.user.v1.RspUserDetail.user:type_name -> api.user.v1.UserInfo
	0,  // 5: api.user.v1.ReqUserCreate.user:type_name -> api.user.v1.UserInfo
	0,  // 6: api.user.v1.RspUserCreate.user:type_name -> api.user.v1.UserInfo
	10, // 7: api.user.v1.ReqUserUpdate.reg_time:type_name -> google.protobuf.Timestamp
	0,  // 8: api.user.v1.RspUserUpdate.user:type_name -> api.user.v1.UserInfo
	0,  // 9: api.user.v1.RspUserList.list:type_name -> api.user.v1.UserInfo
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_user_v1_user_proto_init() }
func file_user_v1_user_proto_init() {
	if File_user_v1_user_proto != nil {
		return
	}
	file_user_v1_user_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_v1_user_proto_goTypes,
		DependencyIndexes: file_user_v1_user_proto_depIdxs,
		MessageInfos:      file_user_v1_user_proto_msgTypes,
	}.Build()
	File_user_v1_user_proto = out.File
	file_user_v1_user_proto_goTypes = nil
	file_user_v1_user_proto_depIdxs = nil
}
