// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/topcms/kratos-template/internal/data/model"
)

func newDictionary_type(db *gorm.DB, opts ...gen.DOOption) dictionary_type {
	_dictionary_type := dictionary_type{}

	_dictionary_type.dictionary_typeDo.UseDB(db, opts...)
	_dictionary_type.dictionary_typeDo.UseModel(&model.Dictionary_type{})

	tableName := _dictionary_type.dictionary_typeDo.TableName()
	_dictionary_type.ALL = field.NewAsterisk(tableName)
	_dictionary_type.ID = field.NewInt64(tableName, "id")
	_dictionary_type.TypeCode = field.NewString(tableName, "type_code")
	_dictionary_type.TypeName = field.NewString(tableName, "type_name")
	_dictionary_type.Status = field.NewInt32(tableName, "status")
	_dictionary_type.Sort = field.NewInt32(tableName, "sort")
	_dictionary_type.CreatedAt = field.NewTime(tableName, "created_at")
	_dictionary_type.UpdatedAt = field.NewTime(tableName, "updated_at")
	_dictionary_type.IsDel = field.NewInt32(tableName, "is_del")

	_dictionary_type.fillFieldMap()

	return _dictionary_type
}

type dictionary_type struct {
	dictionary_typeDo dictionary_typeDo

	ALL       field.Asterisk
	ID        field.Int64  // 类型ID
	TypeCode  field.String // 类型code(外显)
	TypeName  field.String // 类型名称
	Status    field.Int32  // 状态(0:禁用,1:启用)
	Sort      field.Int32  // 排序
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间
	IsDel     field.Int32  // 删除标识

	fieldMap map[string]field.Expr
}

func (d dictionary_type) Table(newTableName string) *dictionary_type {
	d.dictionary_typeDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dictionary_type) As(alias string) *dictionary_type {
	d.dictionary_typeDo.DO = *(d.dictionary_typeDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dictionary_type) updateTableName(table string) *dictionary_type {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt64(table, "id")
	d.TypeCode = field.NewString(table, "type_code")
	d.TypeName = field.NewString(table, "type_name")
	d.Status = field.NewInt32(table, "status")
	d.Sort = field.NewInt32(table, "sort")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")
	d.IsDel = field.NewInt32(table, "is_del")

	d.fillFieldMap()

	return d
}

func (d *dictionary_type) WithContext(ctx context.Context) IDictionary_typeDo {
	return d.dictionary_typeDo.WithContext(ctx)
}

func (d dictionary_type) TableName() string { return d.dictionary_typeDo.TableName() }

func (d dictionary_type) Alias() string { return d.dictionary_typeDo.Alias() }

func (d dictionary_type) Columns(cols ...field.Expr) gen.Columns {
	return d.dictionary_typeDo.Columns(cols...)
}

func (d *dictionary_type) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dictionary_type) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 8)
	d.fieldMap["id"] = d.ID
	d.fieldMap["type_code"] = d.TypeCode
	d.fieldMap["type_name"] = d.TypeName
	d.fieldMap["status"] = d.Status
	d.fieldMap["sort"] = d.Sort
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt
	d.fieldMap["is_del"] = d.IsDel
}

func (d dictionary_type) clone(db *gorm.DB) dictionary_type {
	d.dictionary_typeDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dictionary_type) replaceDB(db *gorm.DB) dictionary_type {
	d.dictionary_typeDo.ReplaceDB(db)
	return d
}

type dictionary_typeDo struct{ gen.DO }

type IDictionary_typeDo interface {
	gen.SubQuery
	Debug() IDictionary_typeDo
	WithContext(ctx context.Context) IDictionary_typeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDictionary_typeDo
	WriteDB() IDictionary_typeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDictionary_typeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDictionary_typeDo
	Not(conds ...gen.Condition) IDictionary_typeDo
	Or(conds ...gen.Condition) IDictionary_typeDo
	Select(conds ...field.Expr) IDictionary_typeDo
	Where(conds ...gen.Condition) IDictionary_typeDo
	Order(conds ...field.Expr) IDictionary_typeDo
	Distinct(cols ...field.Expr) IDictionary_typeDo
	Omit(cols ...field.Expr) IDictionary_typeDo
	Join(table schema.Tabler, on ...field.Expr) IDictionary_typeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDictionary_typeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDictionary_typeDo
	Group(cols ...field.Expr) IDictionary_typeDo
	Having(conds ...gen.Condition) IDictionary_typeDo
	Limit(limit int) IDictionary_typeDo
	Offset(offset int) IDictionary_typeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDictionary_typeDo
	Unscoped() IDictionary_typeDo
	Create(values ...*model.Dictionary_type) error
	CreateInBatches(values []*model.Dictionary_type, batchSize int) error
	Save(values ...*model.Dictionary_type) error
	First() (*model.Dictionary_type, error)
	Take() (*model.Dictionary_type, error)
	Last() (*model.Dictionary_type, error)
	Find() ([]*model.Dictionary_type, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Dictionary_type, err error)
	FindInBatches(result *[]*model.Dictionary_type, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Dictionary_type) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDictionary_typeDo
	Assign(attrs ...field.AssignExpr) IDictionary_typeDo
	Joins(fields ...field.RelationField) IDictionary_typeDo
	Preload(fields ...field.RelationField) IDictionary_typeDo
	FirstOrInit() (*model.Dictionary_type, error)
	FirstOrCreate() (*model.Dictionary_type, error)
	FindByPage(offset int, limit int) (result []*model.Dictionary_type, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDictionary_typeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d dictionary_typeDo) Debug() IDictionary_typeDo {
	return d.withDO(d.DO.Debug())
}

func (d dictionary_typeDo) WithContext(ctx context.Context) IDictionary_typeDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d dictionary_typeDo) ReadDB() IDictionary_typeDo {
	return d.Clauses(dbresolver.Read)
}

func (d dictionary_typeDo) WriteDB() IDictionary_typeDo {
	return d.Clauses(dbresolver.Write)
}

func (d dictionary_typeDo) Session(config *gorm.Session) IDictionary_typeDo {
	return d.withDO(d.DO.Session(config))
}

func (d dictionary_typeDo) Clauses(conds ...clause.Expression) IDictionary_typeDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d dictionary_typeDo) Returning(value interface{}, columns ...string) IDictionary_typeDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d dictionary_typeDo) Not(conds ...gen.Condition) IDictionary_typeDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d dictionary_typeDo) Or(conds ...gen.Condition) IDictionary_typeDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d dictionary_typeDo) Select(conds ...field.Expr) IDictionary_typeDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d dictionary_typeDo) Where(conds ...gen.Condition) IDictionary_typeDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d dictionary_typeDo) Order(conds ...field.Expr) IDictionary_typeDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d dictionary_typeDo) Distinct(cols ...field.Expr) IDictionary_typeDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d dictionary_typeDo) Omit(cols ...field.Expr) IDictionary_typeDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d dictionary_typeDo) Join(table schema.Tabler, on ...field.Expr) IDictionary_typeDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d dictionary_typeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDictionary_typeDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d dictionary_typeDo) RightJoin(table schema.Tabler, on ...field.Expr) IDictionary_typeDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d dictionary_typeDo) Group(cols ...field.Expr) IDictionary_typeDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d dictionary_typeDo) Having(conds ...gen.Condition) IDictionary_typeDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d dictionary_typeDo) Limit(limit int) IDictionary_typeDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d dictionary_typeDo) Offset(offset int) IDictionary_typeDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d dictionary_typeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDictionary_typeDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d dictionary_typeDo) Unscoped() IDictionary_typeDo {
	return d.withDO(d.DO.Unscoped())
}

func (d dictionary_typeDo) Create(values ...*model.Dictionary_type) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d dictionary_typeDo) CreateInBatches(values []*model.Dictionary_type, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d dictionary_typeDo) Save(values ...*model.Dictionary_type) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d dictionary_typeDo) First() (*model.Dictionary_type, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dictionary_type), nil
	}
}

func (d dictionary_typeDo) Take() (*model.Dictionary_type, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dictionary_type), nil
	}
}

func (d dictionary_typeDo) Last() (*model.Dictionary_type, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dictionary_type), nil
	}
}

func (d dictionary_typeDo) Find() ([]*model.Dictionary_type, error) {
	result, err := d.DO.Find()
	return result.([]*model.Dictionary_type), err
}

func (d dictionary_typeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Dictionary_type, err error) {
	buf := make([]*model.Dictionary_type, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d dictionary_typeDo) FindInBatches(result *[]*model.Dictionary_type, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d dictionary_typeDo) Attrs(attrs ...field.AssignExpr) IDictionary_typeDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d dictionary_typeDo) Assign(attrs ...field.AssignExpr) IDictionary_typeDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d dictionary_typeDo) Joins(fields ...field.RelationField) IDictionary_typeDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d dictionary_typeDo) Preload(fields ...field.RelationField) IDictionary_typeDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d dictionary_typeDo) FirstOrInit() (*model.Dictionary_type, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dictionary_type), nil
	}
}

func (d dictionary_typeDo) FirstOrCreate() (*model.Dictionary_type, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dictionary_type), nil
	}
}

func (d dictionary_typeDo) FindByPage(offset int, limit int) (result []*model.Dictionary_type, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d dictionary_typeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d dictionary_typeDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d dictionary_typeDo) Delete(models ...*model.Dictionary_type) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *dictionary_typeDo) withDO(do gen.Dao) *dictionary_typeDo {
	d.DO = *do.(*gen.DO)
	return d
}
