// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q               = new(Query)
	Application     *application
	Dept            *dept
	Dictionary      *dictionary
	Dictionary_type *dictionary_type
	Organization    *organization
	Role            *role
	Service         *service
	User            *user
	User_account    *user_account
	User_dept       *user_dept
	User_third      *user_third
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Application = &Q.Application
	Dept = &Q.Dept
	Dictionary = &Q.Dictionary
	Dictionary_type = &Q.Dictionary_type
	Organization = &Q.Organization
	Role = &Q.Role
	Service = &Q.Service
	User = &Q.User
	User_account = &Q.User_account
	User_dept = &Q.User_dept
	User_third = &Q.User_third
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:              db,
		Application:     newApplication(db, opts...),
		Dept:            newDept(db, opts...),
		Dictionary:      newDictionary(db, opts...),
		Dictionary_type: newDictionary_type(db, opts...),
		Organization:    newOrganization(db, opts...),
		Role:            newRole(db, opts...),
		Service:         newService(db, opts...),
		User:            newUser(db, opts...),
		User_account:    newUser_account(db, opts...),
		User_dept:       newUser_dept(db, opts...),
		User_third:      newUser_third(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Application     application
	Dept            dept
	Dictionary      dictionary
	Dictionary_type dictionary_type
	Organization    organization
	Role            role
	Service         service
	User            user
	User_account    user_account
	User_dept       user_dept
	User_third      user_third
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Application:     q.Application.clone(db),
		Dept:            q.Dept.clone(db),
		Dictionary:      q.Dictionary.clone(db),
		Dictionary_type: q.Dictionary_type.clone(db),
		Organization:    q.Organization.clone(db),
		Role:            q.Role.clone(db),
		Service:         q.Service.clone(db),
		User:            q.User.clone(db),
		User_account:    q.User_account.clone(db),
		User_dept:       q.User_dept.clone(db),
		User_third:      q.User_third.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Application:     q.Application.replaceDB(db),
		Dept:            q.Dept.replaceDB(db),
		Dictionary:      q.Dictionary.replaceDB(db),
		Dictionary_type: q.Dictionary_type.replaceDB(db),
		Organization:    q.Organization.replaceDB(db),
		Role:            q.Role.replaceDB(db),
		Service:         q.Service.replaceDB(db),
		User:            q.User.replaceDB(db),
		User_account:    q.User_account.replaceDB(db),
		User_dept:       q.User_dept.replaceDB(db),
		User_third:      q.User_third.replaceDB(db),
	}
}

type queryCtx struct {
	Application     IApplicationDo
	Dept            IDeptDo
	Dictionary      IDictionaryDo
	Dictionary_type IDictionary_typeDo
	Organization    IOrganizationDo
	Role            IRoleDo
	Service         IServiceDo
	User            IUserDo
	User_account    IUser_accountDo
	User_dept       IUser_deptDo
	User_third      IUser_thirdDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Application:     q.Application.WithContext(ctx),
		Dept:            q.Dept.WithContext(ctx),
		Dictionary:      q.Dictionary.WithContext(ctx),
		Dictionary_type: q.Dictionary_type.WithContext(ctx),
		Organization:    q.Organization.WithContext(ctx),
		Role:            q.Role.WithContext(ctx),
		Service:         q.Service.WithContext(ctx),
		User:            q.User.WithContext(ctx),
		User_account:    q.User_account.WithContext(ctx),
		User_dept:       q.User_dept.WithContext(ctx),
		User_third:      q.User_third.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
