// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/topcms/kratos-template/internal/data/model"
)

func newUser_third(db *gorm.DB, opts ...gen.DOOption) user_third {
	_user_third := user_third{}

	_user_third.user_thirdDo.UseDB(db, opts...)
	_user_third.user_thirdDo.UseModel(&model.User_third{})

	tableName := _user_third.user_thirdDo.TableName()
	_user_third.ALL = field.NewAsterisk(tableName)
	_user_third.UserID = field.NewInt64(tableName, "user_id")
	_user_third.SourceType = field.NewInt32(tableName, "source_type")
	_user_third.ThirdID = field.NewString(tableName, "third_id")
	_user_third.Extra = field.NewString(tableName, "extra")

	_user_third.fillFieldMap()

	return _user_third
}

// user_third 用户第三方信息记录表
type user_third struct {
	user_thirdDo user_thirdDo

	ALL        field.Asterisk
	UserID     field.Int64  // 用户ID
	SourceType field.Int32  // 来源类型
	ThirdID    field.String // 第三方标识
	Extra      field.String // 第三方额外信息(用户名,token等)

	fieldMap map[string]field.Expr
}

func (u user_third) Table(newTableName string) *user_third {
	u.user_thirdDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u user_third) As(alias string) *user_third {
	u.user_thirdDo.DO = *(u.user_thirdDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *user_third) updateTableName(table string) *user_third {
	u.ALL = field.NewAsterisk(table)
	u.UserID = field.NewInt64(table, "user_id")
	u.SourceType = field.NewInt32(table, "source_type")
	u.ThirdID = field.NewString(table, "third_id")
	u.Extra = field.NewString(table, "extra")

	u.fillFieldMap()

	return u
}

func (u *user_third) WithContext(ctx context.Context) IUser_thirdDo {
	return u.user_thirdDo.WithContext(ctx)
}

func (u user_third) TableName() string { return u.user_thirdDo.TableName() }

func (u user_third) Alias() string { return u.user_thirdDo.Alias() }

func (u user_third) Columns(cols ...field.Expr) gen.Columns { return u.user_thirdDo.Columns(cols...) }

func (u *user_third) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *user_third) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 4)
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["source_type"] = u.SourceType
	u.fieldMap["third_id"] = u.ThirdID
	u.fieldMap["extra"] = u.Extra
}

func (u user_third) clone(db *gorm.DB) user_third {
	u.user_thirdDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u user_third) replaceDB(db *gorm.DB) user_third {
	u.user_thirdDo.ReplaceDB(db)
	return u
}

type user_thirdDo struct{ gen.DO }

type IUser_thirdDo interface {
	gen.SubQuery
	Debug() IUser_thirdDo
	WithContext(ctx context.Context) IUser_thirdDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUser_thirdDo
	WriteDB() IUser_thirdDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUser_thirdDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUser_thirdDo
	Not(conds ...gen.Condition) IUser_thirdDo
	Or(conds ...gen.Condition) IUser_thirdDo
	Select(conds ...field.Expr) IUser_thirdDo
	Where(conds ...gen.Condition) IUser_thirdDo
	Order(conds ...field.Expr) IUser_thirdDo
	Distinct(cols ...field.Expr) IUser_thirdDo
	Omit(cols ...field.Expr) IUser_thirdDo
	Join(table schema.Tabler, on ...field.Expr) IUser_thirdDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUser_thirdDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUser_thirdDo
	Group(cols ...field.Expr) IUser_thirdDo
	Having(conds ...gen.Condition) IUser_thirdDo
	Limit(limit int) IUser_thirdDo
	Offset(offset int) IUser_thirdDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUser_thirdDo
	Unscoped() IUser_thirdDo
	Create(values ...*model.User_third) error
	CreateInBatches(values []*model.User_third, batchSize int) error
	Save(values ...*model.User_third) error
	First() (*model.User_third, error)
	Take() (*model.User_third, error)
	Last() (*model.User_third, error)
	Find() ([]*model.User_third, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.User_third, err error)
	FindInBatches(result *[]*model.User_third, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.User_third) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUser_thirdDo
	Assign(attrs ...field.AssignExpr) IUser_thirdDo
	Joins(fields ...field.RelationField) IUser_thirdDo
	Preload(fields ...field.RelationField) IUser_thirdDo
	FirstOrInit() (*model.User_third, error)
	FirstOrCreate() (*model.User_third, error)
	FindByPage(offset int, limit int) (result []*model.User_third, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUser_thirdDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u user_thirdDo) Debug() IUser_thirdDo {
	return u.withDO(u.DO.Debug())
}

func (u user_thirdDo) WithContext(ctx context.Context) IUser_thirdDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u user_thirdDo) ReadDB() IUser_thirdDo {
	return u.Clauses(dbresolver.Read)
}

func (u user_thirdDo) WriteDB() IUser_thirdDo {
	return u.Clauses(dbresolver.Write)
}

func (u user_thirdDo) Session(config *gorm.Session) IUser_thirdDo {
	return u.withDO(u.DO.Session(config))
}

func (u user_thirdDo) Clauses(conds ...clause.Expression) IUser_thirdDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u user_thirdDo) Returning(value interface{}, columns ...string) IUser_thirdDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u user_thirdDo) Not(conds ...gen.Condition) IUser_thirdDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u user_thirdDo) Or(conds ...gen.Condition) IUser_thirdDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u user_thirdDo) Select(conds ...field.Expr) IUser_thirdDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u user_thirdDo) Where(conds ...gen.Condition) IUser_thirdDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u user_thirdDo) Order(conds ...field.Expr) IUser_thirdDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u user_thirdDo) Distinct(cols ...field.Expr) IUser_thirdDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u user_thirdDo) Omit(cols ...field.Expr) IUser_thirdDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u user_thirdDo) Join(table schema.Tabler, on ...field.Expr) IUser_thirdDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u user_thirdDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUser_thirdDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u user_thirdDo) RightJoin(table schema.Tabler, on ...field.Expr) IUser_thirdDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u user_thirdDo) Group(cols ...field.Expr) IUser_thirdDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u user_thirdDo) Having(conds ...gen.Condition) IUser_thirdDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u user_thirdDo) Limit(limit int) IUser_thirdDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u user_thirdDo) Offset(offset int) IUser_thirdDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u user_thirdDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUser_thirdDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u user_thirdDo) Unscoped() IUser_thirdDo {
	return u.withDO(u.DO.Unscoped())
}

func (u user_thirdDo) Create(values ...*model.User_third) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u user_thirdDo) CreateInBatches(values []*model.User_third, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u user_thirdDo) Save(values ...*model.User_third) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u user_thirdDo) First() (*model.User_third, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.User_third), nil
	}
}

func (u user_thirdDo) Take() (*model.User_third, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.User_third), nil
	}
}

func (u user_thirdDo) Last() (*model.User_third, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.User_third), nil
	}
}

func (u user_thirdDo) Find() ([]*model.User_third, error) {
	result, err := u.DO.Find()
	return result.([]*model.User_third), err
}

func (u user_thirdDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.User_third, err error) {
	buf := make([]*model.User_third, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u user_thirdDo) FindInBatches(result *[]*model.User_third, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u user_thirdDo) Attrs(attrs ...field.AssignExpr) IUser_thirdDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u user_thirdDo) Assign(attrs ...field.AssignExpr) IUser_thirdDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u user_thirdDo) Joins(fields ...field.RelationField) IUser_thirdDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u user_thirdDo) Preload(fields ...field.RelationField) IUser_thirdDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u user_thirdDo) FirstOrInit() (*model.User_third, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.User_third), nil
	}
}

func (u user_thirdDo) FirstOrCreate() (*model.User_third, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.User_third), nil
	}
}

func (u user_thirdDo) FindByPage(offset int, limit int) (result []*model.User_third, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u user_thirdDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u user_thirdDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u user_thirdDo) Delete(models ...*model.User_third) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *user_thirdDo) withDO(do gen.Dao) *user_thirdDo {
	u.DO = *do.(*gen.DO)
	return u
}
