// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/topcms/kratos-template/internal/data/model"
)

func newUser_dept(db *gorm.DB, opts ...gen.DOOption) user_dept {
	_user_dept := user_dept{}

	_user_dept.user_deptDo.UseDB(db, opts...)
	_user_dept.user_deptDo.UseModel(&model.User_dept{})

	tableName := _user_dept.user_deptDo.TableName()
	_user_dept.ALL = field.NewAsterisk(tableName)
	_user_dept.ID = field.NewInt64(tableName, "id")
	_user_dept.UserID = field.NewInt64(tableName, "user_id")
	_user_dept.DeptID = field.NewInt64(tableName, "dept_id")

	_user_dept.fillFieldMap()

	return _user_dept
}

// user_dept 用户部门关联表
type user_dept struct {
	user_deptDo user_deptDo

	ALL    field.Asterisk
	ID     field.Int64 // 关联ID
	UserID field.Int64 // 用户ID
	DeptID field.Int64 // 部门ID

	fieldMap map[string]field.Expr
}

func (u user_dept) Table(newTableName string) *user_dept {
	u.user_deptDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u user_dept) As(alias string) *user_dept {
	u.user_deptDo.DO = *(u.user_deptDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *user_dept) updateTableName(table string) *user_dept {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt64(table, "id")
	u.UserID = field.NewInt64(table, "user_id")
	u.DeptID = field.NewInt64(table, "dept_id")

	u.fillFieldMap()

	return u
}

func (u *user_dept) WithContext(ctx context.Context) IUser_deptDo {
	return u.user_deptDo.WithContext(ctx)
}

func (u user_dept) TableName() string { return u.user_deptDo.TableName() }

func (u user_dept) Alias() string { return u.user_deptDo.Alias() }

func (u user_dept) Columns(cols ...field.Expr) gen.Columns { return u.user_deptDo.Columns(cols...) }

func (u *user_dept) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *user_dept) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 3)
	u.fieldMap["id"] = u.ID
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["dept_id"] = u.DeptID
}

func (u user_dept) clone(db *gorm.DB) user_dept {
	u.user_deptDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u user_dept) replaceDB(db *gorm.DB) user_dept {
	u.user_deptDo.ReplaceDB(db)
	return u
}

type user_deptDo struct{ gen.DO }

type IUser_deptDo interface {
	gen.SubQuery
	Debug() IUser_deptDo
	WithContext(ctx context.Context) IUser_deptDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUser_deptDo
	WriteDB() IUser_deptDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUser_deptDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUser_deptDo
	Not(conds ...gen.Condition) IUser_deptDo
	Or(conds ...gen.Condition) IUser_deptDo
	Select(conds ...field.Expr) IUser_deptDo
	Where(conds ...gen.Condition) IUser_deptDo
	Order(conds ...field.Expr) IUser_deptDo
	Distinct(cols ...field.Expr) IUser_deptDo
	Omit(cols ...field.Expr) IUser_deptDo
	Join(table schema.Tabler, on ...field.Expr) IUser_deptDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUser_deptDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUser_deptDo
	Group(cols ...field.Expr) IUser_deptDo
	Having(conds ...gen.Condition) IUser_deptDo
	Limit(limit int) IUser_deptDo
	Offset(offset int) IUser_deptDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUser_deptDo
	Unscoped() IUser_deptDo
	Create(values ...*model.User_dept) error
	CreateInBatches(values []*model.User_dept, batchSize int) error
	Save(values ...*model.User_dept) error
	First() (*model.User_dept, error)
	Take() (*model.User_dept, error)
	Last() (*model.User_dept, error)
	Find() ([]*model.User_dept, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.User_dept, err error)
	FindInBatches(result *[]*model.User_dept, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.User_dept) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUser_deptDo
	Assign(attrs ...field.AssignExpr) IUser_deptDo
	Joins(fields ...field.RelationField) IUser_deptDo
	Preload(fields ...field.RelationField) IUser_deptDo
	FirstOrInit() (*model.User_dept, error)
	FirstOrCreate() (*model.User_dept, error)
	FindByPage(offset int, limit int) (result []*model.User_dept, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUser_deptDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u user_deptDo) Debug() IUser_deptDo {
	return u.withDO(u.DO.Debug())
}

func (u user_deptDo) WithContext(ctx context.Context) IUser_deptDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u user_deptDo) ReadDB() IUser_deptDo {
	return u.Clauses(dbresolver.Read)
}

func (u user_deptDo) WriteDB() IUser_deptDo {
	return u.Clauses(dbresolver.Write)
}

func (u user_deptDo) Session(config *gorm.Session) IUser_deptDo {
	return u.withDO(u.DO.Session(config))
}

func (u user_deptDo) Clauses(conds ...clause.Expression) IUser_deptDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u user_deptDo) Returning(value interface{}, columns ...string) IUser_deptDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u user_deptDo) Not(conds ...gen.Condition) IUser_deptDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u user_deptDo) Or(conds ...gen.Condition) IUser_deptDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u user_deptDo) Select(conds ...field.Expr) IUser_deptDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u user_deptDo) Where(conds ...gen.Condition) IUser_deptDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u user_deptDo) Order(conds ...field.Expr) IUser_deptDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u user_deptDo) Distinct(cols ...field.Expr) IUser_deptDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u user_deptDo) Omit(cols ...field.Expr) IUser_deptDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u user_deptDo) Join(table schema.Tabler, on ...field.Expr) IUser_deptDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u user_deptDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUser_deptDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u user_deptDo) RightJoin(table schema.Tabler, on ...field.Expr) IUser_deptDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u user_deptDo) Group(cols ...field.Expr) IUser_deptDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u user_deptDo) Having(conds ...gen.Condition) IUser_deptDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u user_deptDo) Limit(limit int) IUser_deptDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u user_deptDo) Offset(offset int) IUser_deptDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u user_deptDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUser_deptDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u user_deptDo) Unscoped() IUser_deptDo {
	return u.withDO(u.DO.Unscoped())
}

func (u user_deptDo) Create(values ...*model.User_dept) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u user_deptDo) CreateInBatches(values []*model.User_dept, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u user_deptDo) Save(values ...*model.User_dept) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u user_deptDo) First() (*model.User_dept, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.User_dept), nil
	}
}

func (u user_deptDo) Take() (*model.User_dept, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.User_dept), nil
	}
}

func (u user_deptDo) Last() (*model.User_dept, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.User_dept), nil
	}
}

func (u user_deptDo) Find() ([]*model.User_dept, error) {
	result, err := u.DO.Find()
	return result.([]*model.User_dept), err
}

func (u user_deptDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.User_dept, err error) {
	buf := make([]*model.User_dept, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u user_deptDo) FindInBatches(result *[]*model.User_dept, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u user_deptDo) Attrs(attrs ...field.AssignExpr) IUser_deptDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u user_deptDo) Assign(attrs ...field.AssignExpr) IUser_deptDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u user_deptDo) Joins(fields ...field.RelationField) IUser_deptDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u user_deptDo) Preload(fields ...field.RelationField) IUser_deptDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u user_deptDo) FirstOrInit() (*model.User_dept, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.User_dept), nil
	}
}

func (u user_deptDo) FirstOrCreate() (*model.User_dept, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.User_dept), nil
	}
}

func (u user_deptDo) FindByPage(offset int, limit int) (result []*model.User_dept, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u user_deptDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u user_deptDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u user_deptDo) Delete(models ...*model.User_dept) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *user_deptDo) withDO(do gen.Dao) *user_deptDo {
	u.DO = *do.(*gen.DO)
	return u
}
