// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/topcms/kratos-template/internal/data/model"
)

func newUser_account(db *gorm.DB, opts ...gen.DOOption) user_account {
	_user_account := user_account{}

	_user_account.user_accountDo.UseDB(db, opts...)
	_user_account.user_accountDo.UseModel(&model.User_account{})

	tableName := _user_account.user_accountDo.TableName()
	_user_account.ALL = field.NewAsterisk(tableName)
	_user_account.UserID = field.NewInt64(tableName, "user_id")
	_user_account.Password = field.NewString(tableName, "password")
	_user_account.Salt = field.NewString(tableName, "salt")
	_user_account.CreatedAt = field.NewTime(tableName, "created_at")
	_user_account.UpdatedAt = field.NewTime(tableName, "updated_at")
	_user_account.IsDel = field.NewInt32(tableName, "is_del")

	_user_account.fillFieldMap()

	return _user_account
}

// user_account 用户账号表
type user_account struct {
	user_accountDo user_accountDo

	ALL       field.Asterisk
	UserID    field.Int64  // 用户ID
	Password  field.String // 密码
	Salt      field.String // 盐
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间
	IsDel     field.Int32  // 删除标识

	fieldMap map[string]field.Expr
}

func (u user_account) Table(newTableName string) *user_account {
	u.user_accountDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u user_account) As(alias string) *user_account {
	u.user_accountDo.DO = *(u.user_accountDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *user_account) updateTableName(table string) *user_account {
	u.ALL = field.NewAsterisk(table)
	u.UserID = field.NewInt64(table, "user_id")
	u.Password = field.NewString(table, "password")
	u.Salt = field.NewString(table, "salt")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")
	u.IsDel = field.NewInt32(table, "is_del")

	u.fillFieldMap()

	return u
}

func (u *user_account) WithContext(ctx context.Context) IUser_accountDo {
	return u.user_accountDo.WithContext(ctx)
}

func (u user_account) TableName() string { return u.user_accountDo.TableName() }

func (u user_account) Alias() string { return u.user_accountDo.Alias() }

func (u user_account) Columns(cols ...field.Expr) gen.Columns {
	return u.user_accountDo.Columns(cols...)
}

func (u *user_account) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *user_account) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 6)
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["password"] = u.Password
	u.fieldMap["salt"] = u.Salt
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
	u.fieldMap["is_del"] = u.IsDel
}

func (u user_account) clone(db *gorm.DB) user_account {
	u.user_accountDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u user_account) replaceDB(db *gorm.DB) user_account {
	u.user_accountDo.ReplaceDB(db)
	return u
}

type user_accountDo struct{ gen.DO }

type IUser_accountDo interface {
	gen.SubQuery
	Debug() IUser_accountDo
	WithContext(ctx context.Context) IUser_accountDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUser_accountDo
	WriteDB() IUser_accountDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUser_accountDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUser_accountDo
	Not(conds ...gen.Condition) IUser_accountDo
	Or(conds ...gen.Condition) IUser_accountDo
	Select(conds ...field.Expr) IUser_accountDo
	Where(conds ...gen.Condition) IUser_accountDo
	Order(conds ...field.Expr) IUser_accountDo
	Distinct(cols ...field.Expr) IUser_accountDo
	Omit(cols ...field.Expr) IUser_accountDo
	Join(table schema.Tabler, on ...field.Expr) IUser_accountDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUser_accountDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUser_accountDo
	Group(cols ...field.Expr) IUser_accountDo
	Having(conds ...gen.Condition) IUser_accountDo
	Limit(limit int) IUser_accountDo
	Offset(offset int) IUser_accountDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUser_accountDo
	Unscoped() IUser_accountDo
	Create(values ...*model.User_account) error
	CreateInBatches(values []*model.User_account, batchSize int) error
	Save(values ...*model.User_account) error
	First() (*model.User_account, error)
	Take() (*model.User_account, error)
	Last() (*model.User_account, error)
	Find() ([]*model.User_account, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.User_account, err error)
	FindInBatches(result *[]*model.User_account, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.User_account) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUser_accountDo
	Assign(attrs ...field.AssignExpr) IUser_accountDo
	Joins(fields ...field.RelationField) IUser_accountDo
	Preload(fields ...field.RelationField) IUser_accountDo
	FirstOrInit() (*model.User_account, error)
	FirstOrCreate() (*model.User_account, error)
	FindByPage(offset int, limit int) (result []*model.User_account, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUser_accountDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u user_accountDo) Debug() IUser_accountDo {
	return u.withDO(u.DO.Debug())
}

func (u user_accountDo) WithContext(ctx context.Context) IUser_accountDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u user_accountDo) ReadDB() IUser_accountDo {
	return u.Clauses(dbresolver.Read)
}

func (u user_accountDo) WriteDB() IUser_accountDo {
	return u.Clauses(dbresolver.Write)
}

func (u user_accountDo) Session(config *gorm.Session) IUser_accountDo {
	return u.withDO(u.DO.Session(config))
}

func (u user_accountDo) Clauses(conds ...clause.Expression) IUser_accountDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u user_accountDo) Returning(value interface{}, columns ...string) IUser_accountDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u user_accountDo) Not(conds ...gen.Condition) IUser_accountDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u user_accountDo) Or(conds ...gen.Condition) IUser_accountDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u user_accountDo) Select(conds ...field.Expr) IUser_accountDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u user_accountDo) Where(conds ...gen.Condition) IUser_accountDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u user_accountDo) Order(conds ...field.Expr) IUser_accountDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u user_accountDo) Distinct(cols ...field.Expr) IUser_accountDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u user_accountDo) Omit(cols ...field.Expr) IUser_accountDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u user_accountDo) Join(table schema.Tabler, on ...field.Expr) IUser_accountDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u user_accountDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUser_accountDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u user_accountDo) RightJoin(table schema.Tabler, on ...field.Expr) IUser_accountDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u user_accountDo) Group(cols ...field.Expr) IUser_accountDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u user_accountDo) Having(conds ...gen.Condition) IUser_accountDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u user_accountDo) Limit(limit int) IUser_accountDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u user_accountDo) Offset(offset int) IUser_accountDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u user_accountDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUser_accountDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u user_accountDo) Unscoped() IUser_accountDo {
	return u.withDO(u.DO.Unscoped())
}

func (u user_accountDo) Create(values ...*model.User_account) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u user_accountDo) CreateInBatches(values []*model.User_account, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u user_accountDo) Save(values ...*model.User_account) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u user_accountDo) First() (*model.User_account, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.User_account), nil
	}
}

func (u user_accountDo) Take() (*model.User_account, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.User_account), nil
	}
}

func (u user_accountDo) Last() (*model.User_account, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.User_account), nil
	}
}

func (u user_accountDo) Find() ([]*model.User_account, error) {
	result, err := u.DO.Find()
	return result.([]*model.User_account), err
}

func (u user_accountDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.User_account, err error) {
	buf := make([]*model.User_account, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u user_accountDo) FindInBatches(result *[]*model.User_account, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u user_accountDo) Attrs(attrs ...field.AssignExpr) IUser_accountDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u user_accountDo) Assign(attrs ...field.AssignExpr) IUser_accountDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u user_accountDo) Joins(fields ...field.RelationField) IUser_accountDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u user_accountDo) Preload(fields ...field.RelationField) IUser_accountDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u user_accountDo) FirstOrInit() (*model.User_account, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.User_account), nil
	}
}

func (u user_accountDo) FirstOrCreate() (*model.User_account, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.User_account), nil
	}
}

func (u user_accountDo) FindByPage(offset int, limit int) (result []*model.User_account, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u user_accountDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u user_accountDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u user_accountDo) Delete(models ...*model.User_account) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *user_accountDo) withDO(do gen.Dao) *user_accountDo {
	u.DO = *do.(*gen.DO)
	return u
}
