// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAccount = "ts_account"

// Account 账号表
type Account struct {
	UserID    int32          `gorm:"column:user_id;type:int(11) unsigned;primaryKey;autoIncrement:true;comment:用户ID" json:"user_id"` // 用户ID
	UserPwd   string         `gorm:"column:user_pwd;type:varchar(64);not null;comment:账号密码" json:"user_pwd"`                         // 账号密码
	LoginNum  int32          `gorm:"column:login_num;type:int(10) unsigned;not null;comment:登录次数" json:"login_num"`                  // 登录次数
	Salt      string         `gorm:"column:salt;type:varchar(32);not null;comment:主加密key" json:"salt"`                               // 主加密key
	Salt2     string         `gorm:"column:salt2;type:varchar(32);not null;comment:二次加密key" json:"salt2"`                            // 二次加密key
	State     int32          `gorm:"column:state;type:tinyint(3) unsigned;not null;comment:状态" json:"state"`                         // 状态
	CreatedBy string         `gorm:"column:created_by;type:varchar(20);not null;comment:创建人" json:"created_by"`                      // 创建人
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime;not null;comment:创建时间" json:"created_at"`                        // 创建时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`                                 // 删除时间
}

// TableName Account's table name
func (*Account) TableName() string {
	return TableNameAccount
}
