// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAdmin = "ts_admin"

// Admin mapped from table <ts_admin>
type Admin struct {
	ID            int64          `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;comment:主键id" json:"id"`          // 主键id
	Username      string         `gorm:"column:username;type:varchar(255);not null;comment:用户名" json:"username"`                  // 用户名
	Password      string         `gorm:"column:password;type:varchar(255);not null;comment:密码" json:"password"`                   // 密码
	Salt          string         `gorm:"column:salt;type:varchar(255);not null;comment:密码盐" json:"salt"`                          // 密码盐
	Mobile        string         `gorm:"column:mobile;type:varchar(255);not null;comment:手机号" json:"mobile"`                      // 手机号
	Nickname      string         `gorm:"column:nickname;type:varchar(255);not null;comment:昵称" json:"nickname"`                   // 昵称
	Avatar        string         `gorm:"column:avatar;type:varchar(255);not null;comment:头像" json:"avatar"`                       // 头像
	Role          string         `gorm:"column:role;type:varchar(255);not null;comment:角色" json:"role"`                           // 角色
	LastLoginTime string         `gorm:"column:last_login_time;type:varchar(255);not null;comment:上次登录时间" json:"last_login_time"` // 上次登录时间
	LastLoginIP   string         `gorm:"column:last_login_ip;type:varchar(255);not null;comment:上次登录ip" json:"last_login_ip"`     // 上次登录ip
	Domain        string         `gorm:"column:domain;type:varchar(255);not null;comment:域" json:"domain"`                        // 域
	Status        bool           `gorm:"column:status;type:tinyint(1);not null;comment:状态0冻结1正常" json:"status"`                   // 状态0冻结1正常
	CreatedAt     time.Time      `gorm:"column:created_at;type:datetime;not null;comment:创建时间" json:"created_at"`                 // 创建时间
	UpdatedAt     time.Time      `gorm:"column:updated_at;type:datetime;not null;comment:更新时间" json:"updated_at"`                 // 更新时间
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`                          // 删除时间
}

// TableName Admin's table name
func (*Admin) TableName() string {
	return TableNameAdmin
}
