// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameApplication = "m_application"

// Application 应用记录表
type Application struct {
	AppID       int64     `gorm:"column:app_id;type:bigint(20) unsigned;primaryKey;comment:应用记录ID" json:"app_id"` // 应用记录ID
	AppName     string    `gorm:"column:app_name;type:varchar(64);not null;comment:应用名称" json:"app_name"`         // 应用名称
	Description string    `gorm:"column:description;type:varchar(255);not null;comment:描述" json:"description"`    // 描述
	Status      int32     `gorm:"column:status;type:tinyint(1);not null;default:1;comment:状态" json:"status"`      // 状态
	CreatedAt   time.Time `gorm:"column:created_at;type:datetime;not null;comment:创建时间" json:"created_at"`        // 创建时间
	UpdatedAt   time.Time `gorm:"column:updated_at;type:datetime;not null;comment:更新时间" json:"updated_at"`        // 更新时间
	IsDel       int32     `gorm:"column:is_del;type:tinyint(1);not null;comment:删除标识" json:"is_del"`              // 删除标识
}

// TableName Application's table name
func (*Application) TableName() string {
	return TableNameApplication
}
