// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDept = "m_dept"

// Dept 部门表
type Dept struct {
	DeptID    int64     `gorm:"column:dept_id;type:bigint(20) unsigned;primaryKey;comment:部门ID" json:"dept_id"`   // 部门ID
	ParentID  int64     `gorm:"column:parent_id;type:bigint(20);not null;comment:父级ID" json:"parent_id"`          // 父级ID
	DeptCode  string    `gorm:"column:dept_code;type:varchar(32);not null;comment:部门code(用于外显)" json:"dept_code"` // 部门code(用于外显)
	DeptName  string    `gorm:"column:dept_name;type:varchar(64);not null;comment:部门名称" json:"dept_name"`         // 部门名称
	CreatedAt time.Time `gorm:"column:created_at;type:datetime;not null;comment:创建时间" json:"created_at"`          // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;type:datetime;not null;comment:更新时间" json:"updated_at"`          // 更新时间
	IsDel     int32     `gorm:"column:is_del;type:tinyint(1);not null;comment:删除标识" json:"is_del"`                // 删除标识
}

// TableName Dept's table name
func (*Dept) TableName() string {
	return TableNameDept
}
