// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDictionary = "m_dictionary"

// Dictionary 数据字典表
type Dictionary struct {
	ID        int64     `gorm:"column:id;type:bigint(20) unsigned;primaryKey;comment:字典ID" json:"id"`                 // 字典ID
	DictCode  string    `gorm:"column:dict_code;type:varchar(64);not null;comment:字典code(外显)" json:"dict_code"`       // 字典code(外显)
	DictName  string    `gorm:"column:dict_name;type:varchar(128);not null;comment:字典名称" json:"dict_name"`            // 字典名称
	DictType  int64     `gorm:"column:dict_type;type:bigint(20);not null;comment:字典类型ID" json:"dict_type"`            // 字典类型ID
	Status    int32     `gorm:"column:status;type:tinyint(1);not null;default:1;comment:状态(0:禁用,1:启用)" json:"status"` // 状态(0:禁用,1:启用)
	Sort      int32     `gorm:"column:sort;type:int(11);not null;comment:排序" json:"sort"`                             // 排序
	CreatedAt time.Time `gorm:"column:created_at;type:datetime;not null;comment:创建时间" json:"created_at"`              // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;type:datetime;not null;comment:更新时间" json:"updated_at"`              // 更新时间
	IsDel     int32     `gorm:"column:is_del;type:tinyint(1);not null;comment:删除标识" json:"is_del"`                    // 删除标识
}

// TableName Dictionary's table name
func (*Dictionary) TableName() string {
	return TableNameDictionary
}
