// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDictionary_type = "m_dictionary_type"

// Dictionary_type mapped from table <m_dictionary_type>
type Dictionary_type struct {
	ID        int64     `gorm:"column:id;type:bigint(20) unsigned;primaryKey;comment:类型ID" json:"id"`                 // 类型ID
	TypeCode  string    `gorm:"column:type_code;type:varchar(64);not null;comment:类型code(外显)" json:"type_code"`       // 类型code(外显)
	TypeName  string    `gorm:"column:type_name;type:varchar(128);not null;comment:类型名称" json:"type_name"`            // 类型名称
	Status    int32     `gorm:"column:status;type:tinyint(1);not null;default:1;comment:状态(0:禁用,1:启用)" json:"status"` // 状态(0:禁用,1:启用)
	Sort      int32     `gorm:"column:sort;type:int(11);not null;comment:排序" json:"sort"`                             // 排序
	CreatedAt time.Time `gorm:"column:created_at;type:datetime;not null;comment:创建时间" json:"created_at"`              // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;type:datetime;not null;comment:更新时间" json:"updated_at"`              // 更新时间
	IsDel     int32     `gorm:"column:is_del;type:tinyint(1);not null;comment:删除标识" json:"is_del"`                    // 删除标识
}

// TableName Dictionary_type's table name
func (*Dictionary_type) TableName() string {
	return TableNameDictionary_type
}
