// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrganization = "m_organization"

// Organization 组织表
type Organization struct {
	OrgID       int64     `gorm:"column:org_id;type:bigint(20) unsigned;primaryKey;comment:组织ID" json:"org_id"` // 组织ID
	OrgCode     string    `gorm:"column:org_code;type:varchar(32);not null;comment:组织Code(外显)" json:"org_code"` // 组织Code(外显)
	OrgName     string    `gorm:"column:org_name;type:varchar(64);not null;comment:组织名称" json:"org_name"`       // 组织名称
	Description string    `gorm:"column:description;type:varchar(255);not null;comment:描述" json:"description"`  // 描述
	Status      int32     `gorm:"column:status;type:tinyint(1);not null;default:1;comment:状态" json:"status"`    // 状态
	CreatedAt   time.Time `gorm:"column:created_at;type:datetime;not null;comment:创建时间" json:"created_at"`      // 创建时间
	UpdatedAt   time.Time `gorm:"column:updated_at;type:datetime;not null;comment:更新时间" json:"updated_at"`      // 更新时间
	IsDel       int32     `gorm:"column:is_del;type:tinyint(1);not null;comment:删除标识" json:"is_del"`            // 删除标识
}

// TableName Organization's table name
func (*Organization) TableName() string {
	return TableNameOrganization
}
