// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRole = "m_role"

// Role 权限表
type Role struct {
	RoleID    int64     `gorm:"column:role_id;type:bigint(20) unsigned;primaryKey;comment:权限ID" json:"role_id"`       // 权限ID
	RoleCode  string    `gorm:"column:role_code;type:varchar(32);not null;comment:权限标识(外显)" json:"role_code"`         // 权限标识(外显)
	RoleName  string    `gorm:"column:role_name;type:varchar(64);not null;comment:权限名称" json:"role_name"`             // 权限名称
	Status    int32     `gorm:"column:status;type:tinyint(1);not null;default:1;comment:状态(0:禁用,1:启用)" json:"status"` // 状态(0:禁用,1:启用)
	CreatedAt time.Time `gorm:"column:created_at;type:datetime;not null;comment:创建时间" json:"created_at"`              // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;type:datetime;not null;comment:更新时间" json:"updated_at"`              // 更新时间
	IsDel     int32     `gorm:"column:is_del;type:tinyint(1);not null;comment:删除标识" json:"is_del"`                    // 删除标识
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
