// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameService = "m_service"

// Service 服务表
type Service struct {
	ServiceID   int64     `gorm:"column:service_id;type:bigint(20) unsigned;primaryKey;comment:服务ID" json:"service_id"` // 服务ID
	ServiceCode string    `gorm:"column:service_code;type:varchar(32);not null;comment:服务标识(外显)" json:"service_code"`   // 服务标识(外显)
	ServiceName string    `gorm:"column:service_name;type:varchar(64);not null;comment:服务名称" json:"service_name"`       // 服务名称
	Status      int32     `gorm:"column:status;type:tinyint(1);not null;default:1;comment:服务状态" json:"status"`          // 服务状态
	CreatedAt   time.Time `gorm:"column:created_at;type:datetime;not null;comment:创建时间" json:"created_at"`              // 创建时间
	UpdatedAt   time.Time `gorm:"column:updated_at;type:datetime;not null;comment:更新时间" json:"updated_at"`              // 更新时间
	IsDel       int32     `gorm:"column:is_del;type:tinyint(1);not null;comment:删除标识" json:"is_del"`                    // 删除标识
}

// TableName Service's table name
func (*Service) TableName() string {
	return TableNameService
}
