// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser_account = "m_user_account"

// User_account 用户账号表
type User_account struct {
	UserID    int64     `gorm:"column:user_id;type:bigint(20) unsigned;primaryKey;comment:用户ID" json:"user_id"` // 用户ID
	Password  string    `gorm:"column:password;type:varchar(255);not null;comment:密码" json:"password"`          // 密码
	Salt      string    `gorm:"column:salt;type:varchar(8);not null;comment:盐" json:"salt"`                     // 盐
	CreatedAt time.Time `gorm:"column:created_at;type:datetime;not null;comment:创建时间" json:"created_at"`        // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;type:datetime;not null;comment:更新时间" json:"updated_at"`        // 更新时间
	IsDel     int32     `gorm:"column:is_del;type:tinyint(1);not null;comment:删除标识" json:"is_del"`              // 删除标识
}

// TableName User_account's table name
func (*User_account) TableName() string {
	return TableNameUser_account
}
