// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "m_user"

// User 用户基础信息表
type User struct {
	UserID       int64     `gorm:"column:user_id;type:bigint(20) unsigned;primaryKey;comment:用户ID" json:"user_id"`   // 用户ID
	UserCode     string    `gorm:"column:user_code;type:varchar(32);not null;comment:用户code(显示ID)" json:"user_code"` // 用户code(显示ID)
	UserName     string    `gorm:"column:user_name;type:varchar(64);not null;comment:用户名" json:"user_name"`          // 用户名
	Avatar       string    `gorm:"column:avatar;type:varchar(128);not null;comment:头像" json:"avatar"`                // 头像
	Gender       int32     `gorm:"column:gender;type:tinyint(1);not null;comment:性别(0:未知,1:男,2:女)" json:"gender"`    // 性别(0:未知,1:男,2:女)
	Introduction string    `gorm:"column:introduction;type:varchar(255);not null;comment:简介" json:"introduction"`    // 简介
	RegType      int32     `gorm:"column:reg_type;type:tinyint(1);not null;comment:注册类型" json:"reg_type"`            // 注册类型
	RegTime      time.Time `gorm:"column:reg_time;type:datetime;not null;comment:注册时间" json:"reg_time"`              // 注册时间
	RegIP        int32     `gorm:"column:reg_ip;type:int(10);not null;comment:注册IP" json:"reg_ip"`                   // 注册IP
	Country      string    `gorm:"column:country;type:varchar(32);not null;comment:国家" json:"country"`               // 国家
	Province     string    `gorm:"column:province;type:varchar(32);not null;comment:省份" json:"province"`             // 省份
	City         string    `gorm:"column:city;type:varchar(32);not null;comment:城市" json:"city"`                     // 城市
	Lang         string    `gorm:"column:lang;type:varchar(16);not null;comment:语言" json:"lang"`                     // 语言
	CreatedAt    time.Time `gorm:"column:created_at;type:datetime;not null;comment:创建时间" json:"created_at"`          // 创建时间
	UpdatedAt    time.Time `gorm:"column:updated_at;type:datetime;not null;comment:更新时间" json:"updated_at"`          // 更新时间
	IsDel        int32     `gorm:"column:is_del;type:tinyint(1);not null;comment:删除标识" json:"is_del"`                // 删除标识
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
