// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "ts_user"

// User 用户表
type User struct {
	ID          int32          `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true;comment:用户ID" json:"id"` // 用户ID
	UserCode    *string        `gorm:"column:user_code;type:varchar(20);comment:用户编号" json:"user_code"`                      // 用户编号
	UserName    *string        `gorm:"column:user_name;type:varchar(30);comment:用户名称" json:"user_name"`                      // 用户名称
	UserType    *string        `gorm:"column:user_type;type:varchar(20);comment:用户类型" json:"user_type"`                      // 用户类型
	RealName    *string        `gorm:"column:real_name;type:varchar(30);comment:真实姓名" json:"real_name"`                      // 真实姓名
	UserDesc    *string        `gorm:"column:user_desc;type:varchar(200);comment:个人描述" json:"user_desc"`                     // 个人描述
	Email       *string        `gorm:"column:email;type:varchar(120);comment:邮箱" json:"email"`                               // 邮箱
	Gender      *int32         `gorm:"column:gender;type:tinyint(3) unsigned;comment:性别" json:"gender"`                      // 性别
	Tel         *string        `gorm:"column:tel;type:varchar(20);comment:固定电话" json:"tel"`                                  // 固定电话
	Mobile      *string        `gorm:"column:mobile;type:varchar(20);comment:手机号码" json:"mobile"`                            // 手机号码
	DeptCode    *string        `gorm:"column:dept_code;type:varchar(20);comment:所属部门" json:"dept_code"`                      // 所属部门
	Avatar      *string        `gorm:"column:avatar;type:varchar(200);comment:头像" json:"avatar"`                             // 头像
	AvatarThumb *string        `gorm:"column:avatar_thumb;type:varchar(200);comment:头像缩略图" json:"avatar_thumb"`              // 头像缩略图
	IsAccount   *int32         `gorm:"column:is_account;type:tinyint(3) unsigned;comment:账号标识" json:"is_account"`            // 账号标识
	State       *int32         `gorm:"column:state;type:tinyint(3) unsigned;comment:状态" json:"state"`                        // 状态
	CreatedBy   *string        `gorm:"column:created_by;type:varchar(20);comment:创建人" json:"created_by"`                     // 创建人
	CreatedAt   *time.Time     `gorm:"column:created_at;type:datetime;comment:创建时间" json:"created_at"`                       // 创建时间
	UpdatedBy   *string        `gorm:"column:updated_by;type:varchar(20);comment:更新人" json:"updated_by"`                     // 更新人
	UpdatedAt   *time.Time     `gorm:"column:updated_at;type:datetime;comment:更新时间" json:"updated_at"`                       // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`                       // 删除时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
