// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser_third = "m_user_third"

// User_third 用户第三方信息记录表
type User_third struct {
	UserID     int64  `gorm:"column:user_id;type:bigint(20) unsigned;primaryKey;comment:用户ID" json:"user_id"` // 用户ID
	SourceType int32  `gorm:"column:source_type;type:tinyint(1);not null;comment:来源类型" json:"source_type"`    // 来源类型
	ThirdID    string `gorm:"column:third_id;type:varchar(64);not null;comment:第三方标识" json:"third_id"`        // 第三方标识
	Extra      string `gorm:"column:extra;type:text;not null;comment:第三方额外信息(用户名,token等)" json:"extra"`       // 第三方额外信息(用户名,token等)
}

// TableName User_third's table name
func (*User_third) TableName() string {
	return TableNameUser_third
}
