// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser_dept = "m_user_dept"

// User_dept 用户部门关联表
type User_dept struct {
	ID     int64 `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:关联ID" json:"id"` // 关联ID
	UserID int64 `gorm:"column:user_id;type:bigint(20);not null;comment:用户ID" json:"user_id"`                     // 用户ID
	DeptID int64 `gorm:"column:dept_id;type:bigint(20);not null;comment:部门ID" json:"dept_id"`                     // 部门ID
}

// TableName User_dept's table name
func (*User_dept) TableName() string {
	return TableNameUser_dept
}
